= Project structure
:icons: font

include::./includes/attributes.adoc[]

== OneCx Quarkus project structure

OneCx Quarkus project is [Maven](https://maven.apache.org/) project.We use default maven structure which includes: java code and resources, helm templates and dockerfile.

[source]
----
.github
src
  main
     docker
        Dockerfile.jvm
        Dockerfile.native
     helm
        Chart.yaml
        values.yaml
     openapi
        example-openapi.yaml
     java
     resources
       application.properties
  test
     java
     resources
pom.xml
----
The helm template are in the `src/main/helm` and dockerfile is in the `src/main/docker/Dockerfile` directory.

GitHub project configuration is defined in the `.github` directory. For more information please check next chapter xref:quarkus-github-actions.adoc[Project GitHub Actions]

IMPORTANT: Onecx Quarkus project GitHub Actions xref:quarkus-github-actions.adoc[Project GitHub Actions] setup.

== Java naming convention

Basically all our microservice consist of 3 main layers

* Endpoint components providing REST api to outside world.
* IntermediateService which implements business logic. These components are often omitted.
* Entity services are components taking care of data management, basically fetching storing the data from/to database

Java classes:

* RestController – Any class named RestController is supposed to expose API to outside world  For example: `UserRestController`
* Service – (IntermediateService) the core components containing business logic, shareable piece of codes for other components usually controllers or other services as well. For example: `UserValidationService`
* Mapper - Object mapper. For example: `UserMapper`.
* DAO - Data access object (JPA entity wrapper) For example: `UserDAO`

Each project should have own package which contains the domain of the project.
All projects start with a package `{project-structure-package}` and package `<groupId>.<artefactId | simplified>`

For example our Maven project:

* groupId = `{project-structure-package}.example`
* artefactId = `onecx-quarkus-example`

[source,java,subs=attributes+]
----
{project-structure-package}.quarkus.example
----

Model and REST packages:
[source,java,subs=attributes+]
----
domain.models  // JPA entities
domain.daos // DAO and search criteria for the entities
domain.services // Common shared domain services
rs // common rs classes (CORSFilter, JaxRSActivator..)
rs.internal.controllers // REST controllers
rs.internal.mappers // internal DTOs mappers
rs.<version>.controllers // REST controllers
rs.<version>.logs // log mappers
rs.<version>.mappers // external DTOs mappers
rs.subdomain.<version>.controllers // subdomain REST controllers
rs.subdomain.<version>.logs // log mappers
rs.subdomain.<version>.mappers // subdomain DTOs mappers
----

Example application
[source,java,subs=attributes+]
----
{project-structure-package}.quarkus.example.domain.models  // JPA entities
{project-structure-package}.quarkus.example.domain.daos // DAO for the entities
{project-structure-package}.quarkus.example.domain.services // DAO for the entities
{project-structure-package}.quarkus.example.rs //common rs classes (CORSFilter, JaxRSActivator..)
{project-structure-package}.quarkus.example.rs.internal.controllers // REST controllers
{project-structure-package}.quarkus.example.rs.internal.mappers // internal DTOs mappers
{project-structure-package}.quarkus.example.rs.<version>.controllers // REST controllers
{project-structure-package}.quarkus.example.rs.<version>.mappers // external DTOs mappers
----

[IMPORTANT]
.For the rest-controllers we need to have two types of the rest endpoints:
====
  * internal - which are us only for the internal domain, for example for UI
  * <version | external> - these REST controllers are external interfaces to rest of the world. For these we need to have version.
====

== Docker

In the project we do have defined two docker files one for java base docker image and one for native build docker image. Source code of base docker image is in the GitHub repository {docker-quarkus-jvm-url}[docker-quarkus-native] and {docker-quarkus-jvm-url}[docker-quarkus-jvm].

In the project we define corresponding `Dockerfiles`

.Dockerfile.jvm definition
[%collapsible%open]
====
[source,dockerfile,subs=attributes+]
----
FROM ghcr.io/onecx/docker-quarkus-jvm:{docker-quarkus-jvm-version}

COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/
USER 185
----
====

.Dockerfile.native definition
[%collapsible%open]
====
[source,dockerfile,subs=attributes+]
----
FROM ghcr.io/onecx/docker-quarkus-native:{docker-quarkus-native-version}

COPY --chown=1001:root target/*-runner /work/application
----
====

[IMPORTANT]
Docker build configuration is defined in the {onecx-quarkus3-parent-url}[{onecx-quarkus3-parent-artifact-id}]

[TIP]
For more information about Quarkus docker extension check the official documentation {quarkus-url}container-image[quarkus-container-image-docker].

== Helm

In the `src/main/helm` we muss defined `Chart.yaml` in version `v2` and `values.yaml`. Helm chart of the service muss use the {helm-quarkus-app-name} helm dependencies. Alias for all onecx quarkus application is `{helm-quarkus-app-alias}`. GitHub pipeline replace chart `version` and `appVersion` during the build with current service version.

.Chart.yaml
[%collapsible%open]
====
[source,yaml,subs=attributes+]
----
apiVersion: v2
name: onecx-example-svc
version: 0.0.0
appVersion: 0.0.0
description: Onecx example service
keywords:
  - example
sources:
  - https://github.com/onecx/onecx-example-svc
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: {helm-quarkus-app-name}
    alias: {helm-quarkus-app-alias}
    version: {helm-quarkus-app-version}
    repository: {helm-quarkus-app-repo}
----
====

.values.yaml
[%collapsible%open]
====
[source,yaml,subs=attributes+]
----
app:
  name: svc
  image:
    repository: "onecx/onecx-example-svc"
  db:
    enabled: true
----
====

In our example we did activate the `database` configuration `app.db.enabled: true`.

[IMPORTANT]
For product base delivery `helm-of-helm` we do need to specify the `app.name`, which is the name of the component in the product (for example svc, bff, operator).

[NOTE]
For more details of the helm template configuration check the repository of {helm-quarkus-app-url}[{helm-quarkus-app-name}]

[TIP]
Helm documentation {helm-url}[helm].
