= Project structure
:icons: font

include::./includes/attributes.adoc[]

TIP: The source code of the sample application is located in the documentation repository https://github.com/onecx/docs-guides-quarkus/tree/main/docs/modules/quarkus/examples/quarkus/base/example[Base example]

== OneCx Quarkus project structure

OneCx Quarkus project is https://maven.apache.org/[Maven] project.We use default maven structure which includes: java code and resources, helm templates and dockerfile.

[source,java]
----
include::example$quarkus/base/snippets/structure.txt[]
----

The helm template are in the `src/main/helm` and dockerfile is in the `src/main/docker` directory.

GitHub project configuration is defined in the `.github` directory. For more information please check next chapter xref:quarkus-github-actions.adoc[Project GitHub Actions]

IMPORTANT: Onecx Quarkus project GitHub Actions xref:quarkus-github-actions.adoc[Project GitHub Actions] setup.

== Maven configuration

Onecx project are using
[source,xml,subs=attributes+]
----
include::example$quarkus/base/example/pom.xml[tag=parent,indent=0]
----

== Java naming convention

[mermaid]
....
flowchart LR
    classDef service fill:#adebb3,stroke:#333
    classDef external fill:#b5c7eb,stroke:#333
    n(Client):::external --> b
    subgraph microservice
    b(Boundary service):::service --> e1
    b --> c
    b --> i(Intermediate service):::service
    i --> e1(Entity services):::service
    i --> c(Client services):::service
    end
    e1 --> db[(Database)]:::external
    c --> e>External system]:::external
....

Basically all our microservice consist of 3 main layers

* Boundary components providing REST api ( or AMQP, Events, ...) to outside world.
* IntermediateService which implements business logic. These components are often omitted.
* Entity services are components taking care of data management, basically fetching storing the data from/to database
* Client services which are

Java classes:

Validation request sequence:
[mermaid]
....
sequenceDiagram
    UserRestController->>+UserMapper: map DTO request to internal model
    UserMapper-->>-UserRestController: internal model
    UserRestController->>+UserValidationService: validate user request
    UserValidationService-->>-UserRestController: validation result
....

Create user request sequence:
[mermaid]
....
sequenceDiagram
    UserRestController->>+UserMapper: map DTO request to internal model
    UserMapper-->>-UserRestController: internal model
    UserRestController->>+UserDAO: create user
    UserDAO-->>-UserRestController: created user
    UserRestController->>+UserMapper: map internal model to DTO
    UserMapper-->>-UserRestController: DTO model
....

 * RestController – Any class named RestController is supposed to expose API to outside world  For example: `UserRestController`
* Service – (IntermediateService) the core components containing business logic, shareable piece of codes for other components usually controllers or other services as well. For example:  `UserValidationService`
* Mapper - Object mapper for mapping DTO to internal models and vice versa. For example: `UserMapper`.
* DAO - Data access object (JPA entity wrapper) For example: `UserDAO`

Each project should have own package which contains the domain of the project.
All projects in the `onecx` context start with a package `{project-structure-package}` and package `<artefactId | simplified>`

For example our Maven project:

* groupId = `{project-structure-package}`
* artefactId = `onecx-quarkus-example`

[source,shell,subs=attributes+]
----
src
    main
        java
            {project-structure-package}.quarkus.example
----

Microservice package structure:
[source,java,subs=attributes+]
----
include::example$quarkus/base/snippets/packages.txt[]
----

Our xref:example$quarkus/base/example/src/main/java/org/tkit/onecx[{project-structure-package}] package of our example application.
[source,java,subs=attributes+]
----
include::example$quarkus/base/snippets/packages-example.txt[]
----

[IMPORTANT]
.For the rest-controllers we need to have two types of the rest endpoints:
====
  * internal - which are us only for the internal domain, for example for UI
  * <version | external> - these REST controllers are external interfaces to rest of the world. For these we need to have version.
====

== Docker

In the project we have defined two docker files, one for java base docker image and one for native build docker image. The source code for the base docker image can be found in the GitHub repositories {docker-quarkus-jvm-url}[docker-quarkus-native] and {docker-quarkus-jvm-url}[docker-quarkus-jvm].

The two `Dockerfiles` look like this:

.Dockerfile.jvm definition

[source,dockerfile,subs=attributes+]
----
include::example$quarkus/base/example/src/main/docker/Dockerfile.jvm[]
----

.Dockerfile.native definition
[source,dockerfile,subs=attributes+]
----
include::example$quarkus/base/example/src/main/docker/Dockerfile.native[]
----

[IMPORTANT]
Docker build configuration is defined in the maven parent project.

[TIP]
For more information about Quarkus docker extension, please check the official documentation {quarkus-url}container-image[quarkus-container-image-docker].

== Helm

In the `src/main/helm` we muss define `Chart.yaml` in version `v2` and `values.yaml`. The alias for every onecx quarkus application is `{helm-quarkus-app-alias}`. The GitHub pipeline will replace the chart `version` and `appVersion` during the build with current service version.

.Chart.yaml
[source,yaml,subs=attributes+]
----
include::example$quarkus/base/example/src/main/helm/Chart.yaml[]
----

.values.yaml
[source,yaml,subs=attributes+]
----
include::example$quarkus/base/example/src/main/helm/values.yaml[]
----

In our example we did activate the `database` configuration `app.db.enabled: true`.

[IMPORTANT]
For product base delivery `helm-of-helm` we do need to specify the `app.name`, which is the name of the component in the product (for example svc, bff, operator).

[NOTE]
For more details of the helm template configuration check the repository of {helm-quarkus-app-url}[{helm-quarkus-app-name}]

[TIP]
Helm documentation {helm-url}[helm].
